const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/biocodex_v7.html','utf8');
const m=html.match(/<script id="bxcore">([\s\S]*?)<\/script>/); assert(m,'core script block found');
const mod={exports:{}}; new Function('module',m[1])(mod); const BX=mod.exports;
let n=0; const t=(name,fn)=>{fn(); n++; console.log('ok',n,name);};
const close=(a,b,eps=1e-9)=>assert(Math.abs(a-b)<eps,`${a} != ${b}`);

t('clean strips non-IUPAC and maps U->T',()=>assert.equal(BX.clean('ac gu\n12t'),'ACGTT'));
t('2-bit code ACGT -> 00011011',()=>assert.equal(BX.toBits('ACGT'),'00011011'));
t('packed byte ACGT = 0x1B',()=>{assert.deepEqual(BX.toBytes('ACGT'),[27]); assert.equal(BX.hex2(27),'1B');});
t('padding: 5 bases -> 2 bytes, ambiguous -> -1',()=>{assert.deepEqual(BX.toBytes('ACGTA'),[27,0]); assert.deepEqual(BX.toBytes('ACGN'),[-1]);});
t('ascii8 A',()=>assert.equal(BX.ascii8('A'),'01000001'));
t('counts + GC',()=>{const s=BX.stats('AACCGGTTN'); assert.equal(s.counts.other,1); close(s.gc,0.5);});
t('GC skew',()=>close(BX.stats('GGGC').gcSkew,0.5));
t('entropy uniform = 2 bits, single = 0',()=>{close(BX.entropy('ACGT'),2); close(BX.entropy('AAAA'),0);});
t('dinucleotide entropy max 4',()=>{let s='';for(const a of 'ACGT')for(const b of 'ACGT')s+=a+b; assert(BX.entropy(s,2)<=4);});
t('kmers top',()=>assert.deepEqual(BX.kmers('AAAAC',3,1),[['AAA',2]]));
t('translate ATGGCCTAA -> MA*',()=>assert.equal(BX.translate('ATGGCCTAA',0),'MA*'));
t('translate ambiguous -> X',()=>assert.equal(BX.translate('ATGNNN',0),'MX'));
t('orfs finds M..stop',()=>{const seq='ATG'+'GCC'.repeat(40)+'TAA'; assert.deepEqual(BX.orfs(seq,0,30),[{start:1,aa:41}]);});
t('codon table has 64 entries, 3 stops',()=>{const k=Object.keys(BX.CODON); assert.equal(k.length,64); assert.equal(k.filter(c=>BX.CODON[c]==='*').length,3);});
t('cgr first point of A = (0.25,0.25)',()=>{const p=BX.cgr('A'); close(p[0],.25); close(p[1],.25);});
t('cgr skips ambiguous',()=>assert.equal(BX.cgr('NN').length,0));
t('zcurve last row',()=>{const z=BX.zcurve('AG',10); const r=z[z.length-1]; assert.deepEqual(r,[2,2,0,0]);});
t('Wallace Tm short',()=>close(BX.stats('ATGC').tm,12));
t('mass ACGT',()=>close(BX.stats('ACGT').mass,313.2+289.2+329.2+304.2-61.96,1e-6));
t('parse multi-FASTA',()=>{const r=BX.parse('>X1 Escherichia coli test\nACGT\nAC\n>X2 desc\nGGG'); assert.equal(r.length,2); assert.equal(r[0].seq,'ACGTAC'); assert.equal(r[0].accession,'X1'); assert.equal(r[0].organism,'Escherichia coli'); assert.equal(r[1].seq,'GGG');});
t('parse GenBank',()=>{const gb='LOCUS       NC_1  12 bp DNA\nDEFINITION  Test phage, complete\n            genome.\nACCESSION   NC_1\n  ORGANISM  Testus phagus\nORIGIN\n        1 acgtac gtacgt\n//\n'; const r=BX.parse(gb); assert.equal(r.length,1); assert.equal(r[0].seq,'ACGTACGTACGT'); assert.equal(r[0].accession,'NC_1'); assert.equal(r[0].organism,'Testus phagus'); assert.equal(r[0].definition,'Test phage, complete genome.');});
t('parse raw',()=>assert.equal(BX.parse('acg tta')[0].seq,'ACGTTA'));
t('parse empty',()=>assert.equal(BX.parse('>only header\n').length,0));
t('human guard',()=>{assert(BX.isHuman('','Homo sapiens')); assert(BX.isHuman('Human','')); assert(!BX.isHuman('Chimpanzee','Pan troglodytes'));});
t('formGenome deterministic',()=>{const a=BX.formGenome('ACGTACGGTC'),b=BX.formGenome('ACGTACGGTC'); assert.deepEqual(a,b); assert(a.m>=3&&a.m<=15);});
t('formGenome differs across sequences',()=>assert.notEqual(BX.formGenome('AAAAAAAAAAAA').seed,BX.formGenome('ACGTACGTACGT').seed));
t('superformula circle for m=0',()=>{const r=BX.superformula({m:0,a:1,b:1,n1:1,n2:1,n3:1},8); r.pts.forEach(p=>close(Math.hypot(p[0],p[1]),1,1e-9));});
t('lsystem growth',()=>assert.equal(BX.lsystem('A',{A:'AB',B:'A'},3),'ABAAB'));
t('parseRules',()=>assert.deepEqual(BX.parseRules('X -> F+X\nF=FF'),{X:'F+X',F:'FF'}));
t('turtle F up',()=>{const t2=BX.turtle('F',90,10); assert.deepEqual(t2.segs.map(v=>Math.round(v)),[0,0,0,-10]);});
t('turtle push/pop restores',()=>{const t2=BX.turtle('[F]F',90,10); assert.equal(t2.segs.length,8); close(t2.segs[4],0); close(t2.segs[5],0);});
t('capsule round trip (v2 upgrades shape)',()=>{const e=[{id:'e1',seq:'ACGT'}]; assert.deepEqual(BX.readCapsule(BX.capsule(e)),[{id:'e1',seq:'ACGT',kind:'dna',members:[]}]);});
t('capsule rejects foreign JSON',()=>assert.throws(()=>BX.readCapsule('{"a":1}')));
t('fmt',()=>assert.equal(BX.fmt(1234567),'1,234,567'));
console.log(`\n${n} passing`);
/* ---- v2 additions ---- */
t('PDB header parse',()=>{const h=BX.parseHeader('101m_A mol:protein length:154  MYOGLOBIN'); assert.equal(h.pdb,'101m'); assert.equal(h.chain,'A'); assert.equal(h.mol,'protein'); assert.equal(h.title,'MYOGLOBIN'); assert.equal(h.accession,'101m_A');});
t('PDB protein record kind',()=>{const r=BX.parse('>101m_A mol:protein length:5  MYO\nMVLSE'); assert.equal(r[0].kind,'protein'); assert.equal(r[0].seq,'MVLSE'); assert.equal(r[0].format,'PDB');});
t('PDB RNA vs DNA kind',()=>{assert.equal(BX.parse('>1x_A mol:na length:4  R\nACGU')[0].kind,'rna'); assert.equal(BX.parse('>1x_A mol:na length:4  D\nACGT')[0].kind,'dna');});
t('RNA keeps U in seq, bits U=11',()=>{const r=BX.parse('>1x_A mol:na length:4  R\nACGU')[0]; assert.equal(r.seq,'ACGU'); assert.equal(BX.toBits('U'),'11');});
t('aaBits A=00000 Y=10011 X=11111',()=>{assert.equal(BX.aaBits('A'),'00000'); assert.equal(BX.aaBits('Y'),'10011'); assert.equal(BX.aaBits('X'),'11111');});
t('pstats mass/charge/gravy',()=>{const p=BX.pstats('KDA'); close(p.mass,128.17+115.09+71.08+18.02,1e-6); assert.equal(p.charge,0); close(p.gravy,(-3.9-3.5+1.8)/3,1e-9);});
t('protein entropy cap 4.32',()=>assert(BX.pstats(BX.AAS).H1<=Math.log2(20)+1e-9));
t('hydropathy window length',()=>assert.equal(BX.hydropathy('MVLSEGEW',9).length,8));
t('lineParser streams two records',()=>{const out=[];const lp=BX.lineParser(r=>out.push(r)); ['>1a_A mol:na length:3  X','ACG','>1b_B mol:protein length:2  Y','MV'].forEach(lp.line); lp.end(); assert.equal(out.length,2); assert.equal(out[1].kind,'protein');});
t('taxonomy tsv parse',()=>{const m=BX.parseTaxonomy('PDB\tCHAIN\tTAX_ID\tSCIENTIFIC_NAME\n101m\tA\t9796\tEquus caballus\n'); assert.deepEqual(m['101m_A'],{taxid:'9796',name:'Equus caballus'});});
t('seqKey distinguishes kind',()=>assert.notEqual(BX.seqKey('dna','ACGT'),BX.seqKey('rna','ACGT')));
t('formGenome works for protein',()=>{const g=BX.formGenome('MVLSEGEWQLVLHVWAKVEAD','protein'); assert(g.m>=3&&isFinite(g.n1));});
t('translate reads RNA',()=>assert.equal(BX.translate('AUGGCCUAA',0),'MA*'));
t('capsule v1 upgrade adds kind/members',()=>{const e=BX.readCapsule(JSON.stringify({fw:'BIOCODEX',v:1,entries:[{id:'x',seq:'ACGT',accession:'Q'}]})); assert.equal(e[0].kind,'dna'); assert.deepEqual(e[0].members,['Q']);});
console.log(`${n} passing (v2 total)`);
/* ---- v3: 3D ---- */
t('helix B-DNA params from source',()=>{const h=BX.helix('ACGTACGTACGT','dna'); assert.equal(h.params.bpTurn,10.5); close(h.params.rise,3.38); assert.equal(h.s1.length,12); assert.equal(h.s2.length,12); assert.equal(h.rungs.length,12);});
t('helix A-RNA single strand 11 bp/turn',()=>{const h=BX.helix('ACGU','rna'); assert.equal(h.params.bpTurn,11); assert.equal(h.s2.length,0);});
t('helix one full turn returns to angle',()=>{const h=BX.helix('A'.repeat(22),'rna'); close(h.s1[0][0],h.s1[11][0],1e-9); close(h.s1[0][1],h.s1[11][1],1e-9);});
t('helix rise per bp',()=>{const h=BX.helix('ACGT','dna'); close(h.s1[1][2]-h.s1[0][2],3.38,1e-9);});
t('helix cap',()=>{const h=BX.helix('A'.repeat(1000),'dna',600); assert.equal(h.n,600); assert(h.truncated);});
t('sf3d sphere when all params 1',()=>{const m=BX.sf3d({m:0,a:1,b:1,n1:1,n2:1,n3:1},{m:0,a:1,b:1,n1:1,n2:1,n3:1},4,8); m.verts.forEach(v=>close(Math.hypot(v[0],v[1],v[2]),1,1e-9));});
t('sf3d faces count',()=>{const m=BX.sf3d({m:3,a:1,b:1,n1:1,n2:1,n3:1},{m:2,a:1,b:1,n1:1,n2:1,n3:1},4,8); assert.equal(BX.sf3dFaces(m).length,32);});
t('objSurface is valid OBJ',()=>{const m=BX.sf3d({m:3,a:1,b:1,n1:1,n2:1,n3:1},{m:2,a:1,b:1,n1:1,n2:1,n3:1},4,8); const o=BX.objSurface(m,'x'); assert.equal((o.match(/^v /gm)||[]).length,45); assert.equal((o.match(/^f /gm)||[]).length,32); o.split('\n').filter(l=>l.startsWith('f ')).forEach(l=>l.split(' ').slice(1).forEach(i=>assert(+i>=1&&+i<=45)));});
t('objHelix strands + rungs',()=>{const o=BX.objHelix(BX.helix('ACGT','dna'),'t'); assert.equal((o.match(/^v /gm)||[]).length,8); assert.equal((o.match(/^l /gm)||[]).length,3+3+4);});
t('rot3 preserves length',()=>{const r=BX.rot3([1,2,3],0.7,-1.1); close(Math.hypot(r[0],r[1],r[2]),Math.hypot(1,2,3),1e-9);});
console.log(`${n} passing (v3 total)`);
/* ---- v4: Catalogue of Life ---- */
t('normName strips authorship/subgenus',()=>{assert.equal(BX.normName('Panthera leo (Linnaeus, 1758)'),'Panthera leo'); assert.equal(BX.normName('Drosophila (Sophophora) melanogaster Meigen'),'Drosophila melanogaster');});
t('TextTree parser builds hierarchy, skips synonyms',()=>{const got=[];const p=BX.textTreeParser(t=>got.push(t));['Animalia [kingdom]','  Chordata [phylum]','    Mammalia [class]','      Carnivora [order]','        Felidae Fischer, 1817 [family]','          Panthera Oken, 1816 [genus]','            Panthera leo (Linnaeus, 1758) [species]','            =Felis leo Linnaeus, 1758 [species]','            Panthera tigris (Linnaeus, 1758) [species]'].forEach(p.line); p.end();
  assert.equal(got.length,8); const leo=got.find(x=>x.name==='Panthera leo'); assert.equal(leo.rank,'species'); assert.equal(got.find(x=>x.id===leo.parent).name,'Panthera'); assert.equal(got[4].name,'Felidae');});
t('ColDP NameUsage tsv parser filters synonyms',()=>{const got=[];const p=BX.tsvTaxonParser(t=>got.push(t));['col:ID\tcol:parentID\tcol:status\tcol:rank\tcol:scientificName','1\t\taccepted\tkingdom\tAnimalia','2\t1\taccepted\tspecies\tPanthera leo','3\t1\tsynonym\tspecies\tFelis leo'].forEach(p.line); assert.equal(got.length,2); assert.equal(got[1].parent,'1'); assert.equal(got[1].name,'Panthera leo');});
t('DwC Taxon tsv parser',()=>{const got=[];const p=BX.tsvTaxonParser(t=>got.push(t));['dwc:taxonID\tdwc:parentNameUsageID\tdwc:acceptedNameUsageID\tdwc:taxonomicStatus\tdwc:taxonRank\tdwc:scientificName','A\t\tA\taccepted\tgenus\tPanthera Oken, 1816','B\tA\tB\taccepted\tspecies\tPanthera leo (Linnaeus, 1758)'].forEach(p.line); assert.equal(got.length,2); assert.equal(got[0].name,'Panthera'); assert.equal(got[1].name,'Panthera leo');});
t('detectTaxonFormat',()=>{assert.equal(BX.detectTaxonFormat('col:ID\tcol:scientificName'),'tsv'); assert.equal(BX.detectTaxonFormat('Animalia [kingdom]'),'texttree'); assert.equal(BX.detectTaxonFormat('>1abc_A mol:na'),null);});
t('Registry lineage + match species/genus',()=>{const r=new BX.Registry(); [['k','Animalia','kingdom',null],['g','Panthera','genus','k'],['s','Panthera leo','species','g']].forEach(a=>r.add({id:a[0],name:a[1],rank:a[2],parent:a[3]}));
  assert.deepEqual(r.lineage('s').map(x=>x.name),['Animalia','Panthera','Panthera leo']); assert.deepEqual(r.match('Panthera leo (Linnaeus)'),{id:'s',how:'species'}); assert.deepEqual(r.match('Panthera onca'),{id:'g',how:'genus'}); assert.equal(r.match('Canis lupus'),null); assert.equal(r.species.length,1);});
t('Registry search + JSON round trip',()=>{const r=new BX.Registry(); r.add({id:'s',name:'Panthera leo',rank:'species',parent:null,full:'Panthera leo (Linnaeus, 1758)'}); const r2=BX.Registry.fromJSON(JSON.parse(JSON.stringify(r.toJSON()))); assert.equal(r2.search('leo')[0].full,'Panthera leo (Linnaeus, 1758)');});
console.log(`${n} passing (v4 total)`);
/* ---- v5: batch registry ---- */
t('mountBatch prefixes ids and links parents',()=>{const r=new BX.Registry(); const n=r.mountBatch({dsnames:['ioc','usda'],taxa:[[0,'Aves','class',null,'',[],[],[],1],[1,'Corvus corax','species',0,'Corvus corax Linnaeus, 1758',[['Extinction Status',['extant','',3]]],['Common Raven'],['Chad','Germany'],3]]}); assert.equal(n,2); assert.deepEqual(r.lineage('b1').map(x=>x.name),['Aves','Corvus corax']); assert.deepEqual(r.dsList(r.taxa.b1),['ioc','usda']);});
t('vernacular search',()=>{const r=new BX.Registry(); r.mountBatch({dsnames:[],taxa:[[1,'Corvus corax','species',null,'',[],['Common Raven'],[],0]]}); assert.equal(r.search('raven')[0].name,'Corvus corax');});
t('fossil detection',()=>{const r=new BX.Registry(); const t1={traits:[['Fossil First',['66','Ma',1]],['Fossil Last',['Holocene','',1]],['Extinction Status',['extinct','',2]]]}; const f=r.fossil(t1); assert(f.extinct); assert.equal(f.first,'66 Ma'); assert.equal(f.last,'Holocene'); assert(!r.fossil({traits:[['Extinction Status',['extant','',1]]]}).any);});
t('builtin taxa excluded from persistence JSON',()=>{const r=new BX.Registry(); r.mountBatch({dsnames:[],taxa:[[1,'X y','species',null,'',[],[],[],0]]}); r.add({id:'u1',name:'Z w',rank:'species',parent:null}); assert.equal(r.toJSON().length,1); assert.equal(r.toJSON()[0][0],'u1');});
console.log(`${n} passing (v5 total)`);
t('v6: registry carries qid + desc through mount and JSON',()=>{const r=new BX.Registry(); r.mountBatch({dsnames:[],taxa:[[1,'Panthera leo','species',null,'',[],[],[],0,'Q140',['ta','சிங்கம் …']]]}); assert.equal(r.taxa.b1.qid,'Q140'); assert.equal(r.taxa.b1.desc[0],'ta'); const r2=new BX.Registry(); r2.add({id:'u',name:'A b',rank:'species',parent:null,qid:'Q1',desc:['en','x']}); assert.equal(BX.Registry.fromJSON(r2.toJSON()).taxa.u.qid,'Q1');});
t('v6: SIFTS parser skips dated # comment line',()=>{const m=BX.parseTaxonomy('# 2026/09/01 - 12:00 | PDB: 45.1 | UniProt: 2026_04\nPDB\tCHAIN\tTAX_ID\tSCIENTIFIC_NAME\n101m\tA\t9755\tPhyseter macrocephalus Linnaeus, 1758\n'); assert.equal(m['101m_A'].name,'Physeter macrocephalus Linnaeus, 1758');});
t('v6: glycine residue mass per ExPASy',()=>{close(BX.pstats('G').mass,57.0519+18.02,1e-6);});
console.log(`${n} passing (v6 total)`);
/* ---- v7: helix ↔ binary ---- */
t('helixBinary ideal sequence: 2 bits/base, efficiency 1',()=>{const h=BX.helixBinary('ACGT'.repeat(21),'dna'); close(h.eff,2); close(h.eta,1); close(h.turns,8); close(h.bitsPerTurn,21); close(h.bytesPerTurn,2.625); close(h.bitsPerA,2/3.38); assert.equal(h.bytes,21);});
t('helixBinary homopolymer: 0 bits, efficiency 0, mass/bit 0',()=>{const h=BX.helixBinary('AAAAAAAA','dna'); close(h.eff,0); close(h.eta,0); assert.equal(h.massPerBit,0);});
t('Chargaff balance 1 for A=T,G=C and lower when skewed',()=>{close(BX.helixBinary('AATTGGCC','dna').chargaff,1); close(BX.helixBinary('AAAAGGGG','dna').chargaff,0);});
t('mass per bit ≈ M/(H·N)',()=>{const h=BX.helixBinary('ACGTACGT','dna'); const m=BX.stats('ACGTACGT').mass; close(h.massPerBit,m/(2*8),1e-9);});
t('bits per gram ideal ≈ 3.9e21 for ~309 Da mean',()=>{const h=BX.helixBinary('ACGT'.repeat(100),'dna'); assert(h.bitsPerGram>3.5e21&&h.bitsPerGram<4.2e21, h.bitsPerGram);});
t('RNA uses A-form constants',()=>{const h=BX.helixBinary('ACGU'.repeat(11),'rna'); close(h.turns,4); close(h.bitsPerA,2/2.55);});
t('proteinBinary ideal log2(20)',()=>{const h=BX.proteinBinary(BX.AAS); close(h.ideal,Math.log2(20)); close(h.eff,Math.log2(20)); close(h.eta,1); assert.equal(h.bytes,Math.ceil(20*5/8));});
console.log(`${n} passing (v7 total)`);
